services:
  backend:
    image: salipagurung/server
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
