name: CI Implementation
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '5.0'

      - name: start backend
        run: |
          cd contact-fox-backend
          npm i
          npm start &
  
      - name: start frontend
        run: |
          cd contact-fox-frontend
          npm i
          npm start &

      - name: run test for registration feature
        run: |
          cd tests
          npm i
          npm run test:e2e ./features/newUserRegistration.feature
