name: CI Implementation
on:
    push:
        branches: [main]
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Chekout code
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 14.x

            - name: start frontend
              run: |
                   cd contact-fox-frontend
                   npm i
                   npm start &
                  
            - name: start backend
              run: |
                   cd contact-fox-backend
                   npm i
                   npm start &